port: 4000
host: 0.0.0.0
safe: false

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://bredah.github.io"

title: Quality Assurance for Development
email: henrique.breda@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Some information and tips about test automation and how to improve
  quality in development.

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

permalink: /:title.html

jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"


theme: # leave it empty

show_post_image_posts_list: false

header:
  image: /assets/patterns/symphony.png

# social
author:
  name: "Quality Assurance for Development"
  short_bio:
    en: Jekyll Blog Theme, Responsive, SEO and Facebook enabled
    it: Jekyll Blog Theme, Responsive, con SEO e integrazione Facebook
  picture: assets/img/profile-60.png

image: /assets/img/profile-225.png

# Social network
twitter_username: bredahe
github_username:  bredah
linkedin_username: hbreda

# github on site
github:
  owner_url: https://github.com/bredah

# translation
translate:
  en:
    latest-posts:  "Latest Posts"
    read-more:  "read more"
    on-word: "on"
    contact: "Contact"
    contact-page: "contact.md"
    read-time: "min read"
    comments: "comments"
    go-to-home-page: "Go to the Home Page"
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"
  pt:
    latest-posts:  "Último Posts"
    read-more:  "mais detalhes"
    on-word: "on"
    contact: "Contato"
    contact-page: "contact.md"
    read-time: "min read"
    comments: "comentários"
    go-to-home-page: "Ir para à página principal"
    months:
      january: "Jan"
      february: "Fev"
      march: "Mar"
      april: "Abr"
      may: "Mai"
      june: "Jun"
      july: "Jul"
      august: "Ago"
      september: "Set"
      october: "Out"
      november: "Nov"
      december : "Dez"

defaults:
  -
    scope:
      type: "posts"
    values:
      lang: "en"
      category: articles